name: Documentation

on:
  push:
    branches:
      - 'master'
    tags: '*'
  pull_request:
jobs:
  Documenter:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Monorepo setup"
        # also dev OndaEDFSchemas.jl for pull request builds
        if: ${{ github.event_name == 'pull_request' }}
        shell: julia --color=yes --project=docs {0}
        run: |
          using Pkg
          Pkg.develop(PackageSpec(; path="./OndaEDFSchemas.jl"))
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-docdeploy@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
