name: Documentation

on:
  push:
    tags: '*'
  pull_request:
jobs:
  Documenter:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Update dependencies"
        # Only use a released version of dependencies when creating documentation for a tag
        if: ${{ github.event_name != 'push' || !startsWith(github.ref, 'refs/tags') }}
        shell: julia --color=yes --project=docs {0}
        run: |
          using Pkg
          Pkg.develop(PackageSpec(; path="./OndaEDFSchemas.jl"))
      - name: "Use latest OndaEDF.jl"
        shell: julia --color=yes --project=docs {0}
        run: |
          using Pkg
          Pkg.develop(PackageSpec(; path="."))
      - uses: julia-actions/julia-docdeploy@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
